# Introdução

Algorítmo de ordenação é um algorítmo (duh?) que organiza os elementos de uma lista de acordo com uma _relação de ordem_ específica. Os tipos mais comuns de relações de ordem são a ordem numérica e a ordem lexicográfica (alfabética).

## PROTIP: diferenciação dos algorítmos

1. Quanto à recursividade: 
   - Não recursivos: Bubble, Insertion e Selection
   - Recursivos: Merge e Quick


2. Quanto à eficiência:
   - Menos eficientes: Bubble, Insertion e Selection
   - Mais eficientes: Merge e Quick

Algorítmos de ordenação recursivos são mais eficientes. :)


# Exercício: Bubble Sort (X min)

Implemente o algorítmo de ordenação não recursivo Bubble Sort. Este algorítmo tem como macro-característica a ordenação da lista do maior elemento para o menor. Cada passo do algorítimo compara dois elementos adjacentes da lista trocando-os de posição caso eles estejam fora de ordem. Ao término do passo, o maior elemento estará na última posição da lista, então, "remove-se" o último elemento da lista e repete o passo enquanto a lista tiver mais de um elemento.

In [4]:
import numpy as np

def bubblesort(lista):
    n = len(lista)
    
    for i in range(n):
        for j in range(0, n - i - 1):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]

In [6]:
v = np.random.randint(0, 100, 20)

print(v)

bubblesort(v)

print(v)

[20 25 53 24 86 27 23 37 92 74 96 39 56  3 34 24 51 64 94 83]
[ 3 20 23 24 24 25 27 34 37 39 51 53 56 64 74 83 86 92 94 96]


# Exercício: Insertion Sort (X min)

Implemente o algorítmo não recursivo Insertion Sort. A ideia principal desse algorítmo é partir de uma sublista ordenada pequena (1 elemento) e, a cada passo, pegar o elemento seguinte da lista original e inserí-lo na posição correta na sublista deslocando os elementos maiores uma casa para a direita.

In [11]:
def insertionsort(lista):
    n = len(lista)
    
    for i in range(n - 1):
        
        tmp = lista[i + 1]
        
        j = i
        while j >= 0 and lista[j] > tmp:
            lista[j + 1] = lista[j]
            j -= 1
            
        lista[j + 1] = tmp

In [12]:
v = np.random.randint(0, 100, 20)

print(v)

insertionsort(v)

print(v)

[86 16 15 60 23 22  7 97 52 14 28 54 94 57 46  5  7 50 55 56]
[ 5  7  7 14 15 16 22 23 28 46 50 52 54 55 56 57 60 86 94 97]


# Exercício: Selection Sort (X min)

Implemente o algorítmo não recursivo Selection Sort. Esse algorítmo consiste em buscar o menor elemento na list inteira e colocá-lo na primeira posição. Em seguida, "elimina-se" o primeiro elemento e repete-se o processo para a lista resultante até todos os elementos estarem ordenados.

In [13]:
def selectionsort(lista):
    n = len(lista)
    
    for i in range(n - 1):
        
        pos_min = i
        for j in range(i + 1, n):
            if lista[j] < lista[pos_min]:
                pos_min = j
                
        lista[i], lista[pos_min] = lista[pos_min], lista[i]

In [15]:
v = np.random.randint(0, 100, 20)

print(v)

selectionsort(v)

print(v)

[51 16 35 22 44 66 37 55 46 16 82 44 76  4 21  8 14 72 92 82]
[ 4  8 14 16 16 21 22 35 37 44 44 46 51 55 66 72 76 82 82 92]


# Exemplo: Merge Sort

Esse algoritmo consiste em dividir a lista em duas metades, ordenar essas metades recursivamente e, em seguida, fundir essas metades colocando os elementos de cada uma delas em sua correta posição.

In [17]:
def intercala(v1, v2):
    n1 = len(v1)
    n2 = len(v2)
    
    i1 = 0
    i2 = 0
    
    res = []
    
    while (i1 < n1 and i2 < n2):
        if v1[i1] < v2[i2]:
            res.append(v1[i1])
            i1 += 1
        else:
            res.append(v2[i2])
            i2 += 1
            
    while i1 < n1:
        res.append(v1[i1])
        i1 += 1
        
    while i2 < n2:
        res.append(v2[i2])
        i2 += 1

    
    return res
    
def mergesort(lista):
    if len(lista) > 1:
        m = len(lista) // 2
        
        mergesort(lista[:m])
        mergesort(lista[m:])
        
        res = intercala(lista[:m], lista[m:])
        
        for i in range(len(lista)):
            lista[i] = res[i]

In [18]:
v = np.random.randint(0, 100, 20)

print(v)

mergesort(v)

print(v)

[ 5 72 37 60 62 62  3 74 12 15 19 22 42 86 56 84 91 35 23 27]
[ 3  5 12 15 19 22 23 27 35 37 42 56 60 62 62 72 74 84 86 91]


# Exemplo: Quick Sort

Esse algoritmo consiste em escolher um pivô (elemento de referência), particionar sua lista original colocando todos os elementos menores que o pivo à sua esquerda e todos os elementos maiores que o pivo a sua direita. Ao final da partição, o pivo estará em sua posição certa. Repete-se o procedimento recursivamente para cada umas das duas metades ignorando o pivô.

In [ ]:
def particiona(lista, inf, sup):
    pivo = lista[sup]
    
    i = inf
    for j in range(inf, sup):
        if lista[j] < pivo:
            lista[i], lista[j] = lista[j], lista[i]
            i += 1
        
    lista[i], lista[sup] = lista[sup], lista[i]
    return i
    
def quicksort(lista, inf, sup):
    if inf < sup:
        p = particiona(lista, inf, sup)
        
        quicksort(lista, inf, p - 1)
        quicksort(lista, p + 1, sup)

In [ ]:
v = np.random.randint(0, 100, 20)

print(v)

quicksort(v, 0, len(v) - 1)

print(v)

# Visualização

https://www.toptal.com/developers/sorting-algorithms